#ifndef CS_ONE_SWEEP_COMMON_CONSTANTS_HLSL
#define CS_ONE_SWEEP_COMMON_CONSTANTS_HLSL

#define ALL_BITS_SET (0xffffffffu)
#define NO_BITS_SET  (0x00000000u)

#endif /* CS_ONE_SWEEP_COMMON_CONSTANTS_HLSL */